language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="6.1"
before_install:
  - chmod +x *.sh
  - nvm install $NODE_VERSION
before_script:
  - source ./start-xvfb.sh
script: 
  # Overwrite default "./mvnw test" so that the integration tests are executed as well.
  - ./mvnw verify
after_success:
- ./upload-serenity-reports.sh
deploy:
  edge: true
  provider: cloudfoundry
  username: tobias.schaefer@novatec-gmbh.de
  password:
    secure: FnO5/IWvt6e9HguJI1LUgOvksIWztu2jwn1eyCAa39/Bb3CHG5cpuYmxo3t+xdV3HcS6OdedXwXlWqM8OBgexxQQVES+cwGKmaQesK+A7iVe7+2U4rj/lW1mCMXAV139zY6EyJymTuuIT+A5rgfyJmYhJZ5ZLqMAxqM+0ifgtAmEyo0RgionFcxCHl+jUnY3OU9kml+KfQgdIzZxQDTWYo6kR6/Zd27TwLOHJ2IE1oWU19D/Aj6l8p6uWhDIVfMaBPOt3sdEe7YYFlQeQkqpuf7jbZxmvPPlcod/aoRgoBar452mSvuAKxLyNUN0qPr53OZmPxqRUCR00HVj0365hz+WUkrl/xJnv44kIrE1r87ggEllPZcCQZCzjnlPcRV6X2sjEHZqKKfz5zn6JO/J2ENEfC/CDcEmOk1Ud28pTeAsn+tQ1wxZFQPvgr6mk+aNDA/MVkm2g7NS8MFw831PgjPDST5dgJ7kmmAOCe6iU01itNRH4Jc+T/mUcDAcOnadrp/5gu/tNWebIU/N1R/kgeLUh+b+4Tt8u4aw6vMRa7GCbwGVO6mH5Ra5Mdj+TnjBn6C62xavIs7c2YQ9LLmzYP+2cSualEF0QVGFbzbpRaw/JV5GDlUifED6hHNjI32RvylwJREegf0XnxBcS6DQTnFaqV2VY321ulRptBRzy1A=
  api: https://api.run.pivotal.io
  organization: tosch
  space: development
  on:
    repo: EduCaMa/Showcase
addons:
  firefox: "42.0"
