language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="6.1"
before_install:
  - chmod +x *.sh
  - nvm install $NODE_VERSION
before_script:
  - source ./start-xvfb.sh
script: 
  # Overwrite default "./mvnw test" so that the integration tests are executed as well.
  - ./mvnw verify
after_success:
- ./upload-serenity-reports.sh
deploy:
  edge: true
  provider: cloudfoundry
  username: martin.schmollinger@reutlingen-university.de
  password:
	secure: x2yoq+kg0F+saISgFjfSWqQW9FLKnV8N+mvotXodISF+g0p+nZD+awtb8DPlTPE+0TEXjluZNy/QNrNMEMZGkW8gKT2Zfal+sD0QGs/aFOTRV8f+N5wHJCQFUYywK0q7zrT/FIU8GsezDorZep62U8QwiZHDoJMpHGjU3WiXJsGeTnphp1KcgOObyPT7LTG8ZPdkmZ50rI8ZVf0n+2vNGvwCY40Nz2OmZ85dL+H2ocrRoUWnGNqGiKdkcIzvFC13J+BSYxblzyNkknO8UTN+mw4zsOmrJIxMQHT057OKkw1nV2lB2iV0XUmX13wVNzZfTBvUwFza8i26TMsiPZg3GhcQqo841mojSUZPD53JNba5yiLK3MHiGfy0nd9gRN4Ekd11t60oMHYi3rDBzqVSXQxAP8HlPE07WgklQ6UaDFdWBfjBeWfVT8OdDvPt+ci4RuwnbxxWQAK66L0+jkNsnErASCyEZjsdNivcvJml+axf9huG/PFT3tKQGK5uVoVeQrtGENw+R+xOUGg6bGlUMbabLwUe2q4uHceGbNHpk2Z9A57uhCUh4HfTOPeQsnokhZ3pobJbk7jwequasM7UeNYTOfP6hSlqpyqWrzMi++jL+vhyaVeLxXWCDYlYVLPW1qKsF+y3Ri/NMt3zCUIXojniCsfcgO3PHwEdKevv4Vs=
  api: https://api.ng.bluemix.net
  organization: EduCaMa
  space: dev
  on:
    repo: EduCaMa/Showcase
addons:
  firefox: "42.0"
